seed: 42
epochs: 10
patience: 3
frames_per_video: 3

dataset:
  mode: "faces" # Đã chuyển sang "faces" để train trên toàn bộ ảnh đã cắt sẵn (nhanh gấp 100 lần)
  video_csv: "master_split.csv"
  faces_csv: "/kaggle/input/datasets/min2k4/face-ff/kaggle/working/ffpp_faces/faces_master.csv"




models:
  meso4:
    type: "custom"
    name: "meso4"
    img_size: 256
    batch_size: 32
    lr: 0.001
  mobilenetv3:
    type: "timm"
    name: "mobilenetv3_large_100"
    img_size: 224
    batch_size: 32
    lr: 0.0001
  efficientnet_b4:
    type: "timm"
    name: "tf_efficientnet_b4.ns_jft_in1k"
    img_size: 380
    batch_size: 8
    lr: 0.0001
  xception:
    type: "timm"
    name: "legacy_xception"
    img_size: 299
    batch_size: 16
    lr: 0.0002
  vit:
    type: "timm"
    name: "vit_small_patch16_224"
    img_size: 224
    batch_size: 16
    lr: 0.00005

